### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ThomasCZ** [davidusb-geek/emhass#876]
**Describe the bug**
After updating to v0.17.4, all POST requests to EMHASS fail with an `AttributeError: 'str' object has no attribute 'get'` in `utils.py` during `compile_heat_topology`. 

This is caused by a regression where the add-on configuration has `"heat_topology": "null"` (the default configuration string for unused heat integration), but the new thermal modeling engine treats it as a raw string instead of an object/dictionary, crashing when it tries to run `.get()`.

**To Reproduce**
1. Have `"heat_topology": "null"` in the add-on configuration (or runtime parameters).
2. Upgrade to v0.17.4.
3. Send any optimization request (e.g., POST `/action/naive-mpc-optim`).
4. The web server crashes with a 500 Internal Server Error.

**Home Assistant installation type**
 - Home Assistant OS - 17.3
 - Home Assistant Supervised - 2026.05.0
 - Home Assistant Core - 2026.5.3

**Your hardware**
- OS: HA OS
- Architecture: rpi5-64

**EMHASS installation type**
 - Add-on (v0.17.4)

**Additional context**
The crash happens here in `emhass/utils.py` at line 509:
```python
def compile_heat_topology(topology: dict) -> dict:
    ...
    sources = topology.get("sources", []) or []
```

Since topology contains the string "null", calling .get() throws the AttributeError.

Temporary Workaround / Fix:
Changing the add-on configuration from:

```
"heat_topology": "null"
```

to a valid empty object:

```
"heat_topology": {
  "sources": []
}
```

immediately resolves the issue and optimization works again. The code should probably be guarded with an isinstance(heat_topology, dict) check or properly handle the "null" string case.

**Logs**

```
[2026-05-21 11:39:31,855] INFO in web_server:  >> Obtaining params: 

[2026-05-21 11:39:31,856] INFO in web_server: Passed runtime parameters: {'pv_power_forecast': [4810, 4869, 3954, 3768, 4660, 3580, 2751, 4151, 4636, 5036, 5091, 2544, 2721, 3216, 3208, 1544, 1852, 3263, 3378, 3032, 1950, 2242, 1963, 2097, 1371, 1441, 1355, 1255, 1032, 880, 652, 282, 270, 186, 125, 42, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'load_cost_forecast': [1.5808, 1.1603, 1.9329, 1.8385, 1.8381, 1.7855, 1.0152, 0.9635, 0.8967, 0.846, 0.8566, 0.9846, 0.9922, 1.0691, 1.7534, 2.0917, 2.9131, 3.4734, 1.5481, 2.7702, 3.4874, 3.8137, 3.0618, 3.6752, 4.0003, 4.4844, 4.1115, 4.5912, 5.1073, 5.1577, 5.7017, 6.0391, 6.3847, 7.2949, 5.9778, 6.5443, 7.2432, 7.5713, 7.1693, 6.5022, 6.044, 5.5264, 6.5334, 5.5767, 5.3098, 5.102, 5.2183, 5.0853, 4.8946, 4.7616], 'prod_price_forecast': [0.4854, 0.1379, 0.1381, 0.0601, 0.0598, 0.0163, 0.018, -0.0248, -0.08, -0.1219, -0.1131, -0.0073, -0.001, 0.0625, -0.0102, 0.2694, 0.9482, 1.4113, 0.4584, 1.4684, 2.0611, 2.3308, 1.7094, 2.2163, 2.485, 2.8851, 2.5769, 2.9733, 3.3999, 3.4415, 3.2528, 3.5317, 3.8173, 4.5695, 4.1193, 4.5875, 5.1651, 5.4362, 5.104, 4.5527, 4.174, 3.7462, 4.5785, 3.7878, 3.5672, 3.3955, 3.4916, 3.3817, 3.2241, 3.1142], 'prediction_horizon': 50, 'soc_init': 0.17, 'historic_days_to_retrieve': 3, 'days_to_retrieve': 3, 'load_forecast_method': 'mlforecaster', 'var_model': 'sensor.emma_load_power', 'sklearn_model': 'GradientBoostingRegressor', 'num_lags': 144}

[2026-05-21 11:39:31,857] INFO in web_server:  >> Setting input data dict

[2026-05-21 11:39:31,857] INFO in command_line: Setting up needed data

[2026-05-21 11:39:31,860] DEBUG in utils: setting`passed_data:days_to_retrieve` to 9 for fit/predict/tune

[2026-05-21 11:39:31,860] ERROR in app: Exception on request POST /action/naive-mpc-optim

Traceback (most recent call last):

  File "/app/.venv/lib/python3.12/site-packages/quart/app.py", line 1464, in handle_request

    return await self.full_dispatch_request(request_context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/quart/app.py", line 1502, in full_dispatch_request

    result = await self.handle_user_exception(error)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/quart/app.py", line 1059, in handle_user_exception

    raise error

  File "/app/.venv/lib/python3.12/site-packages/quart/app.py", line 1500, in full_dispatch_request

    result = await self.dispatch_request(request_context)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/quart/app.py", line 1597, in dispatch_request

    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/src/emhass/web_server.py", line 693, in action_call

    input_data_dict = await set_input_data_dict(

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/src/emhass/command_line.py", line 1079, in set_input_data_dict

    ) = await utils.treat_runtimeparams(

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/src/emhass/utils.py", line 1890, in treat_runtimeparams

    compiled = compile_heat_topology(heat_topology)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/src/emhass/utils.py", line 509, in compile_heat_topology

    sources = topology.get("sources", []) or []

              ^^^^^^^^^^^^

AttributeError: 'str' object has no attribute 'get'
```

**Comment by JVRFI** [comment]
Same here

**Comment by lutorm** [comment]
Seems to be the same problem with the nulls in "cost_forecast_per_deferrable_load", too.

**Comment by lutorm** [comment]
I'm curious why this wasn't flagged by the test suite? IMHO it should not be possible to merge code that totally breaks a vanilla install, that's very disruptive to existing users.

**Comment by OptimalNothing90** [comment]
@lutorm Good catch. Same string-vs-JSON-null footgun as `heat_topology`, just on the Python side. The crash site is `optimization.py` at the `cost_per_load_overrides` loop: `np.asarray("n", dtype=float)` raises `ValueError` once the loop character-indexes the string. So if your config carries `"cost_forecast_per_deferrable_load": "null"` (as a string), the next optimization run will crash.

Traced through the paths: the shipped default `[null, null]` flows through cleanly. Each `None` is detected and the load falls back to the global tariff. So whatever you're hitting needs a non-default value reaching `optim_conf`. Most likely candidates are the string `"null"` (the same shape ThomasCZ has for `heat_topology`) or an array with string entries. Could you share the exact value as it appears in your config? That narrows the fix site.

On the test gap: agreed. Going through the v0.17.3 wave I saw happy-path-only testing across several new params: features work when configured, defaults crash. AGENTS.md already says "zero-config default must keep working" and "smoke-test when schema changes", so the gap isn't the docs, it's enforcement. Nothing checks that `param_definitions.json` ↔ `config_defaults.json` ↔ JS / Python consumers stay in sync.

Schema-contract test drafted as a follow-up PR, plan is to open it once #878 merges. Would appreciate fresh eyes on the test scope before maintainer review.

**Comment by davidusb-geek** [comment]
> I'm curious why this wasn't flagged by the test suite? IMHO it should not be possible to merge code that totally breaks a vanilla install, that's very disruptive to existing users.

Because we need to improve the testing suite.
What do you propose to catch this type of issue?
I'm open to implement what's needed to avoid breaking and disruptive changes like these

**Comment by lutorm** [comment]
@davidusb-geek Just running an optimization with the defaults and ensuring it doesn't crash should catch it, right? Although I guess it must be two cases, one with an empty config to catch the defaults in the code and one that reads the default json?

**Comment by davidusb-geek** [comment]
Launching an optimization with the defaults is the most basic test that we already have since day 0. 
But yes we might need to add the second case

**Comment by lutorm** [comment]
> Launching an optimization with the defaults is the most basic test that we already have since day 0.

That's what I figured, so that's why I was confused.
